// Default content for all website sections
// These are used when no SectionContent record exists in the DB

export const IMAGES = {
  hero: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Prem_Mandir_Vrindavan_2022_02.jpg/1280px-Prem_Mandir_Vrindavan_2022_02.jpg',
  bankeBihari: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Banke_Bihari_Vrindavan.jpg/1280px-Banke_Bihari_Vrindavan.jpg',
  bankeBihariGate: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Bankebihari_temple_main_gate_Vrindavan.JPG/960px-Bankebihari_temple_main_gate_Vrindavan.JPG',
  iskcon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/Iskcon_Vrindavan.jpg/1280px-Iskcon_Vrindavan.jpg',
  premMandirNight: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Prem_Mandir_Night_View.jpg/1280px-Prem_Mandir_Night_View.jpg',
  premMandirDay: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Prem_Mandir_Vrindavan_2022_02.jpg/1280px-Prem_Mandir_Vrindavan_2022_02.jpg',
  dwarkadhish: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Dwarkadhish_Temple_01.JPG/1280px-Dwarkadhish_Temple_01.JPG',
  mathuraCity: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Mathura_Janma_Bhoomi.jpg/1280px-Mathura_Janma_Bhoomi.jpg',
  govardhanHill: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Govardhan_hill.JPG/1280px-Govardhan_hill.JPG',
  govardhanParikrama: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Goverdhan_parikrama_birds.jpg/1280px-Goverdhan_parikrama_birds.jpg',
  radhaRaniTemple: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Shri_Radha_Rani_Temple_Barsana_-_panoramio.jpg/1280px-Shri_Radha_Rani_Temple_Barsana_-_panoramio.jpg',
  barsanaHoli: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Lathmar_Holi_2022_in_Nandgaon%2C_Uttar_Pradesh_%28edited%29.jpg/1280px-Lathmar_Holi_2022_in_Nandgaon%2C_Uttar_Pradesh_%28edited%29.jpg',
  yamunaAarti: 'https://upload.wikimedia.org/wikipedia/commons/6/69/Yamuna_Aarti.jpg',
  keshiGhat: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Keshi_Ghat_Vrindavan.jpg/1280px-Keshi_Ghat_Vrindavan.jpg',
  yamunaRiver: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Yamuna_River_at_Vrindavan.jpg/1280px-Yamuna_River_at_Vrindavan.jpg',
  holiColors: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Holi_Festival_of_Colours.jpg/1280px-Holi_Festival_of_Colours.jpg',
  holiCelebration: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Lathmar_Holi_2022_in_Nandgaon%2C_Uttar_Pradesh_%28edited%29.jpg/1280px-Lathmar_Holi_2022_in_Nandgaon%2C_Uttar_Pradesh_%28edited%29.jpg',
  lathmarHoli: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Lathmar_Holi_2022_in_Nandgaon%2C_Uttar_Pradesh_%28edited%29.jpg/1280px-Lathmar_Holi_2022_in_Nandgaon%2C_Uttar_Pradesh_%28edited%29.jpg',
  pilgrimsWalking: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Goverdhan_parikrama_birds.jpg/1280px-Goverdhan_parikrama_birds.jpg',
  devoteesTemple: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Banke_Bihari_Vrindavan.jpg/1280px-Banke_Bihari_Vrindavan.jpg',
  gokulTemple: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Radha_Krishna_GOKUL.jpg/960px-Radha_Krishna_GOKUL.jpg',
  nandgaon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Nandgaon_Temple.jpg/1280px-Nandgaon_Temple.jpg',
  iskconDeities: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Radha_Krishna_at_Iskcon_Vrindavan.jpg/960px-Radha_Krishna_at_Iskcon_Vrindavan.jpg',
  radhakrishnaDarshan: 'https://upload.wikimedia.org/wikipedia/commons/4/42/Radhakrishna_Darshan_at_Vrundavan.JPG',
  vrindavanOverview: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Prem_Mandir_Vrindavan_2022_02.jpg/1280px-Prem_Mandir_Vrindavan_2022_02.jpg',
  templesReflection: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Keshi_Ghat_Vrindavan.jpg/1280px-Keshi_Ghat_Vrindavan.jpg',
}

export const DEFAULT_SECTION_CONTENT: Record<string, {
  title: string | null
  subtitle: string | null
  content: string | null
}> = {
  hero: {
    title: 'Experience the Divine Essence of Braj Bhoomi',
    subtitle: 'Embark on a sacred journey through the holy land of Lord Krishna — Vrindavan, Mathura, Govardhan, Barsana & beyond. Let devotion guide your path.',
    content: JSON.stringify({
      ctaPrimary: 'Explore Packages',
      ctaSecondary: 'Watch Yatra Video',
      backgroundImage: IMAGES.hero,
    }),
  },
  about: {
    title: 'About Vrindavan Braj Yatra',
    subtitle: 'Your trusted companion for divine pilgrimage experiences in Braj Bhoomi',
    content: JSON.stringify({
      story: 'Vrindavan Braj Yatra was born from a deep love for the sacred land of Braj. For generations, our family has been connected to this holy region — walking the parikrama paths, visiting the ancient temples, and experiencing the divine presence that fills every corner of Vrindavan, Mathura, and the surrounding villages. We started this service to share the authentic Braj experience with devotees from across India and the world.',
      mission: 'To make the sacred Braj Yatra accessible, comfortable, and deeply spiritual for every devotee — regardless of age, background, or budget. We believe that every soul deserves to experience the divine love of Braj Bhoomi.',
      vision: 'To be the most trusted and beloved Braj Yatra service, known for authentic spiritual experiences, exceptional service, and deep devotion to Lord Krishna\'s holy land.',
      whyChooseUs: [
        { title: 'Local Expertise', desc: 'Born and raised in Vrindavan — we know every temple, every ghat, every hidden sacred spot.' },
        { title: 'Comfortable Travel', desc: 'AC vehicles, clean accommodations, and well-planned itineraries for a hassle-free yatra.' },
        { title: 'Authentic Experience', desc: 'Not just sightseeing — we provide proper darshan, katha, and spiritual guidance.' },
        { title: 'Affordable Packages', desc: 'Quality yatra experience at prices that don\'t burden the devotee.' },
        { title: '24/7 Support', desc: 'From booking to completion, our team is always available to assist you.' },
        { title: 'Proper Darshan Planning', desc: 'We time your visits for the best darshan and least crowds.' },
      ],
      image: IMAGES.iskconDeities,
    }),
  },
  highlights: {
    title: 'Sacred Destinations of Braj',
    subtitle: 'Discover the divine places that await you on your Braj Yatra',
    content: JSON.stringify([
      {
        title: 'Vrindavan — The Playground of Krishna',
        description: 'Home to over 5,000 temples including Banke Bihari, ISKCON, and Prem Mandir. Experience the eternal Ras Leela in every corner.',
        image: IMAGES.premMandirNight,
        link: '/destinations/vrindavan',
      },
      {
        title: 'Mathura — The Birthplace of Lord Krishna',
        description: 'Visit the sacred Krishna Janmabhoomi, Dwarkadhish Temple, and the ghats of Yamuna where divine history was born.',
        image: IMAGES.dwarkadhish,
        link: '/destinations/mathura',
      },
      {
        title: 'Govardhan — The Sacred Hill',
        description: 'Perform the divine Govardhan Parikrama (21 km) and visit the sacred Kusum Sarovar, Radha Kund, and Mukharvind.',
        image: IMAGES.govardhanHill,
        link: '/destinations/govardhan',
      },
      {
        title: 'Barsana — Radha Rani\'s Abode',
        description: 'Visit the Shri Radha Rani Temple atop the hill, experience the divine Lathmar Holi, and feel Radha\'s eternal love.',
        image: IMAGES.radhaRaniTemple,
        link: '/destinations/barsana',
      },
    ]),
  },
  packages: {
    title: 'Choose Your Divine Journey',
    subtitle: 'Tailored Braj Yatra packages for every devotee\'s needs and budget',
    content: JSON.stringify({
      packages: [
        {
          id: 'one-day',
          name: 'Same Day Braj Darshan',
          price: '₹1,499',
          pricePer: 'per person',
          duration: '1 Day',
          places: ['Vrindavan Temple Tour', 'Banke Bihari Darshan', 'ISKCON Temple', 'Prem Mandir', 'Mathura (if time permits)'],
          inclusions: ['AC Vehicle', 'Pickup & Drop', 'Driver cum Guide', 'Toll & Parking', 'Water Bottle'],
          exclusions: ['Meals', 'Pooja Samagri', 'Accommodation', 'Entry Tickets'],
          idealFor: 'Devotees with limited time wanting a quick Braj darshan',
          popular: false,
          color: 'braj-teal',
        },
        {
          id: 'two-day',
          name: '2-Day Braj Yatra',
          price: '₹3,499',
          pricePer: 'per person',
          duration: '2 Days / 1 Night',
          places: ['Day 1: Vrindavan Temples', 'Banke Bihari, ISKCON, Prem Mandir', 'Yamuna Aarti at Keshi Ghat', 'Day 2: Mathura — Krishna Janmabhoomi, Dwarkadhish', 'Govardhan Parikrama'],
          inclusions: ['AC Vehicle', '1 Night Stay', 'Breakfast', 'Driver cum Guide', 'Toll & Parking', 'Pickup & Drop'],
          exclusions: ['Lunch & Dinner', 'Pooja Samagri', 'Entry Tickets'],
          idealFor: 'Devotees wanting a complete Braj experience at comfortable pace',
          popular: true,
          color: 'braj-dark-green',
        },
        {
          id: 'three-day',
          name: '3-Day Complete Braj Yatra',
          price: '₹5,999',
          pricePer: 'per person',
          duration: '3 Days / 2 Nights',
          places: ['Day 1: Vrindavan — All Major Temples', 'Day 2: Mathura, Govardhan Parikrama, Radha Kund', 'Day 3: Barsana, Nandgaon, Gokul'],
          inclusions: ['AC Vehicle', '2 Nights Stay', 'Daily Breakfast', 'Driver cum Guide', 'Toll & Parking', 'Pickup & Drop', 'Evening Aarti Experience'],
          exclusions: ['Lunch & Dinner', 'Pooja Samagri', 'Entry Tickets'],
          idealFor: 'Families and devotees wanting the most complete Braj experience',
          popular: false,
          color: 'braj-gold',
        },
        {
          id: 'custom',
          name: 'Custom Braj Yatra',
          price: 'Contact Us',
          pricePer: 'for pricing',
          duration: 'Flexible',
          places: ['Customized itinerary', 'Choose your own destinations', 'Flexible duration', 'Special pooja arrangements', 'Group discounts available'],
          inclusions: ['Fully Customizable', 'AC Vehicle', 'Accommodation', 'Meals as per plan', 'Dedicated Guide', 'Special Darshan Assistance'],
          exclusions: ['Varies as per plan'],
          idealFor: 'Large groups, special occasions, senior citizens, or specific spiritual needs',
          popular: false,
          color: 'braj-saffron',
        },
      ],
    }),
  },
  testimonials: {
    title: 'Blessed Devotees Share Their Experience',
    subtitle: 'Hear from pilgrims who experienced the divine Braj Yatra',
    content: JSON.stringify([
      {
        name: 'Suresh Sharma',
        location: 'Delhi',
        quote: 'The Braj Yatra was a life-changing experience. The guide knew every temple and its history. Banke Bihari darshan was the highlight — truly divine!',
        rating: 5,
        package: '2-Day Braj Yatra',
      },
      {
        name: 'Meera Patel',
        location: 'Mumbai',
        quote: 'I was worried about traveling alone, but the team took such good care of me. The Govardhan Parikrama at sunrise was magical. Highly recommend!',
        rating: 5,
        package: '3-Day Complete Yatra',
      },
      {
        name: 'Rajesh Verma',
        location: 'Jaipur',
        quote: 'Took my elderly parents on the 2-day yatra. The team arranged everything perfectly — comfortable car, good hotel, and proper time at each temple. Parents were very happy.',
        rating: 5,
        package: '2-Day Braj Yatra',
      },
      {
        name: 'Anita Joshi',
        location: 'Pune',
        quote: 'The Yamuna Aarti at Keshi Ghat was mesmerizing. Our guide told us stories about each place that made the whole yatra come alive. Will definitely come again!',
        rating: 4,
        package: '3-Day Complete Yatra',
      },
      {
        name: 'Vikram Singh',
        location: 'Lucknow',
        quote: 'Best pilgrimage tour I\'ve ever taken. The arrangements were top-notch, and the spiritual experience was beyond words. Radhe Radhe!',
        rating: 5,
        package: 'Same Day Darshan',
      },
      {
        name: 'Priya Agarwal',
        location: 'Kolkata',
        quote: 'Barsana and Nandgaon were the hidden gems of our yatra. The local guide knew the exact spots where Krishna and Radha used to meet. Incredible experience!',
        rating: 5,
        package: '3-Day Complete Yatra',
      },
    ]),
  },
  faq: {
    title: 'Frequently Asked Questions',
    subtitle: 'Everything you need to know about your Braj Yatra',
    content: JSON.stringify([
      { question: 'What is the best time to visit Braj Bhoomi?', answer: 'The best time is from October to March when the weather is pleasant. However, major festivals like Holi (March), Janmashtami (August), and Radhashtami (September) offer unique spiritual experiences. Each season has its own charm in Braj.' },
      { question: 'How do I book a Braj Yatra package?', answer: 'You can book by calling us at +91 89239 44869, sending a WhatsApp message, or filling out the enquiry form on our website. We\'ll help you choose the right package and customize it as needed.' },
      { question: 'Is the yatra suitable for elderly devotees?', answer: 'Absolutely! We specialize in making the yatra comfortable for senior citizens. Our vehicles are air-conditioned, we plan rest stops, and our guides are patient and helpful. We can also customize the itinerary to reduce walking.' },
      { question: 'What should I carry for the yatra?', answer: 'Carry comfortable walking shoes, modest clothing for temple visits, a water bottle, sunscreen (in summer), a light shawl/wrap, any personal medications, and a small bag for prasad. We provide water bottles in all packages.' },
      { question: 'Can I customize my yatra package?', answer: 'Yes! Our Custom Braj Yatra package is fully customizable. You can choose your destinations, duration, accommodation type, and even request special pooja arrangements. Contact us to discuss your requirements.' },
      { question: 'What is the Govardhan Parikrama?', answer: 'The Govardhan Parikrama is a sacred circumambulation of Govardhan Hill, covering approximately 21 km. It can be done on foot, by vehicle, or partially both. It\'s believed that Lord Krishna lifted this hill to protect the residents of Braj from Indra\'s wrath.' },
      { question: 'Do you provide pickup from railway station/airport?', answer: 'Yes, we provide pickup and drop from Mathura Junction, Vrindavan railway station, and nearby airports (Agra/Delhi) at reasonable rates. This can be included in your package.' },
      { question: 'Are meals included in the packages?', answer: 'Breakfast is included in 2-day and 3-day packages. Lunch and dinner are not included to give you the flexibility to try local Braj cuisine. We can recommend the best pure vegetarian restaurants.' },
    ]),
  },
  contact: {
    title: 'Plan Your Divine Journey Today',
    subtitle: 'Reach out to us and let the divine journey begin',
    content: JSON.stringify({
      ctaText: 'Let us help you plan your perfect Braj Yatra. Fill out the form below or contact us directly.',
      businessHours: 'Monday - Saturday: 6:00 AM - 9:00 PM | Sunday: 7:00 AM - 6:00 PM',
      whatsappMessage: 'Hello! I am interested in booking a Braj Yatra package. Please share details.',
    }),
  },
  footer: {
    title: null,
    subtitle: null,
    content: JSON.stringify({
      description: 'Vrindavan Braj Yatra — Your trusted companion for divine pilgrimage experiences in the holy land of Braj Bhoomi. We offer authentic, comfortable, and affordable Braj Yatra packages.',
      copyright: '© 2024 Vrindavan Braj Yatra. All rights reserved. | Made with 🙏 in Vrindavan',
    }),
  },
}
